# Generated by Django 4.2 on 2024-04-18 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_file_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='file',
        ),
    ]
